// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package login is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	PingRequest
	PingResponse
	LoginRequest
	LoginResponse
	UserProfile
*/
package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LoginRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LoginResponse struct {
	Result bool         `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	User   *UserProfile `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginResponse) GetUser() *UserProfile {
	if m != nil {
		return m.User
	}
	return nil
}

type UserProfile struct {
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName      string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	ContactNumber string `protobuf:"bytes,3,opt,name=contact_number,json=contactNumber" json:"contact_number,omitempty"`
}

func (m *UserProfile) Reset()                    { *m = UserProfile{} }
func (m *UserProfile) String() string            { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()               {}
func (*UserProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*PingRequest)(nil), "login.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "login.PingResponse")
	proto.RegisterType((*LoginRequest)(nil), "login.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "login.LoginResponse")
	proto.RegisterType((*UserProfile)(nil), "login.UserProfile")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/login.UserService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/login.UserService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/login.UserService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/login.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "login.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _UserService_Ping_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0xb5, 0xb5, 0xa5, 0x30, 0xb4, 0x1e, 0x46, 0xa3, 0x04, 0x2f, 0xcd, 0x26, 0x1a, 0xe2, 0xa1,
	0x89, 0xd5, 0x3f, 0xf0, 0x64, 0x62, 0x6a, 0x83, 0xf1, 0xdc, 0x50, 0x18, 0x09, 0x06, 0x76, 0x71,
	0x17, 0xea, 0xef, 0x1b, 0x96, 0xdd, 0x04, 0x0e, 0x1e, 0xdf, 0x9b, 0xd9, 0xf7, 0xe6, 0xbd, 0x05,
	0xbf, 0x14, 0x79, 0xc1, 0x37, 0xb5, 0x14, 0x8d, 0xc0, 0xb9, 0x06, 0xec, 0x01, 0xfc, 0x7d, 0xc1,
	0xf3, 0x98, 0x7e, 0x5a, 0x52, 0x0d, 0xde, 0x82, 0xd7, 0x2a, 0x92, 0x07, 0x9e, 0x54, 0x14, 0x4c,
	0xd6, 0x93, 0xc8, 0x8b, 0xdd, 0x8e, 0xd8, 0x25, 0x15, 0xb1, 0x08, 0x96, 0xfd, 0xae, 0xaa, 0x05,
	0x57, 0x84, 0x01, 0x2c, 0x2a, 0x52, 0x2a, 0xc9, 0xed, 0xaa, 0x85, 0xec, 0x05, 0x96, 0x6f, 0x9d,
	0xbc, 0x95, 0xbd, 0x81, 0x85, 0x96, 0x2d, 0x32, 0xb3, 0xe9, 0x74, 0xf0, 0x35, 0xc3, 0x10, 0xdc,
	0x3a, 0x51, 0xea, 0x57, 0xc8, 0x2c, 0x98, 0xf6, 0x76, 0x16, 0xb3, 0x77, 0x58, 0x19, 0x11, 0xe3,
	0x77, 0x0d, 0x8e, 0x24, 0xd5, 0x96, 0x8d, 0x16, 0x71, 0x63, 0x83, 0xf0, 0x1e, 0x66, 0x9d, 0x5c,
	0x70, 0xbe, 0x9e, 0x44, 0xfe, 0x16, 0x37, 0x7d, 0xcc, 0x4f, 0x45, 0x72, 0x2f, 0xc5, 0x57, 0x51,
	0x52, 0xac, 0xe7, 0xec, 0x1b, 0xfc, 0x01, 0xf9, 0xff, 0x51, 0xa3, 0x12, 0xa6, 0xe3, 0x12, 0xf0,
	0x0e, 0x2e, 0x52, 0xc1, 0x9b, 0x24, 0x6d, 0x0e, 0xbc, 0xad, 0x8e, 0xc6, 0xd6, 0x8b, 0x57, 0x86,
	0xdd, 0x69, 0x72, 0x7b, 0xea, 0xbd, 0x3e, 0x48, 0x9e, 0x8a, 0x94, 0xf0, 0x11, 0x66, 0x5d, 0x75,
	0x68, 0x8f, 0x1b, 0x74, 0x1e, 0x5e, 0x8e, 0xb8, 0x3e, 0x2b, 0x3b, 0xc3, 0x67, 0x98, 0xeb, 0xf8,
	0x68, 0xe7, 0xc3, 0x46, 0xc3, 0xab, 0x31, 0x69, 0x5f, 0x1d, 0x1d, 0xfd, 0xbb, 0x4f, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xa4, 0x96, 0x84, 0x9b, 0xec, 0x01, 0x00, 0x00,
}
