// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package login is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	PingRequest
	PingResponse
	LoginRequest
	LoginResponse
	UserProfile
*/
package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LoginRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LoginResponse struct {
	Result bool         `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	User   *UserProfile `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginResponse) GetUser() *UserProfile {
	if m != nil {
		return m.User
	}
	return nil
}

type UserProfile struct {
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName      string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	ContactNumber string `protobuf:"bytes,3,opt,name=contact_number,json=contactNumber" json:"contact_number,omitempty"`
}

func (m *UserProfile) Reset()                    { *m = UserProfile{} }
func (m *UserProfile) String() string            { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()               {}
func (*UserProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*PingRequest)(nil), "login.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "login.PingResponse")
	proto.RegisterType((*LoginRequest)(nil), "login.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "login.LoginResponse")
	proto.RegisterType((*UserProfile)(nil), "login.UserProfile")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0xad, 0x69, 0x32, 0x69, 0x3d, 0xac, 0xa0, 0xa1, 0x5e, 0xca, 0x82, 0x12, 0x3c,
	0x14, 0xac, 0x5f, 0x40, 0xf0, 0x24, 0x48, 0x2d, 0x11, 0xcf, 0x25, 0x4d, 0xc6, 0x10, 0x49, 0x76,
	0xe3, 0x4e, 0xa2, 0x5f, 0x5f, 0xb2, 0x7f, 0xa0, 0x39, 0xf4, 0xf8, 0xde, 0x0e, 0xbf, 0x37, 0xf3,
	0x16, 0xa2, 0x5a, 0x96, 0x95, 0x58, 0xb7, 0x4a, 0x76, 0x92, 0x5d, 0x68, 0xc1, 0x1f, 0x20, 0xda,
	0x55, 0xa2, 0x4c, 0xf1, 0xa7, 0x47, 0xea, 0xd8, 0x2d, 0x84, 0x3d, 0xa1, 0xda, 0x8b, 0xac, 0xc1,
	0xd8, 0x5b, 0x79, 0x49, 0x98, 0x06, 0x83, 0xb1, 0xcd, 0x1a, 0xe4, 0x09, 0xcc, 0xcd, 0x2c, 0xb5,
	0x52, 0x10, 0xb2, 0x18, 0x66, 0x0d, 0x12, 0x65, 0xa5, 0x1b, 0x75, 0x92, 0xbf, 0xc0, 0xfc, 0x6d,
	0xc0, 0x3b, 0xec, 0x0d, 0xcc, 0x34, 0xb6, 0x2a, 0xec, 0xa4, 0x3f, 0xc8, 0xd7, 0x82, 0x2d, 0x21,
	0x68, 0x33, 0xa2, 0x3f, 0xa9, 0x8a, 0x78, 0x62, 0xe2, 0x9c, 0xe6, 0xef, 0xb0, 0xb0, 0x10, 0x9b,
	0x77, 0x0d, 0xbe, 0x42, 0xea, 0xeb, 0x4e, 0x43, 0x82, 0xd4, 0x2a, 0x76, 0x0f, 0xd3, 0x01, 0x17,
	0x9f, 0xaf, 0xbc, 0x24, 0xda, 0xb0, 0xb5, 0x39, 0xf3, 0x93, 0x50, 0xed, 0x94, 0xfc, 0xaa, 0x6a,
	0x4c, 0xf5, 0x3b, 0xff, 0x86, 0xe8, 0xc8, 0x3c, 0xbd, 0xd4, 0xa8, 0x84, 0xc9, 0xb8, 0x04, 0x76,
	0x07, 0x97, 0xb9, 0x14, 0x5d, 0x96, 0x77, 0x7b, 0xd1, 0x37, 0x07, 0x1b, 0x1b, 0xa6, 0x0b, 0xeb,
	0x6e, 0xb5, 0xb9, 0x79, 0x36, 0x59, 0x1f, 0xa8, 0x7e, 0xab, 0x1c, 0xd9, 0x23, 0x4c, 0x87, 0xea,
	0x98, 0x5b, 0xee, 0xa8, 0xf3, 0xe5, 0xd5, 0xc8, 0x33, 0xb7, 0xf2, 0xb3, 0x83, 0xaf, 0xff, 0xe9,
	0xe9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x95, 0xf6, 0x86, 0xb6, 0x01, 0x00, 0x00,
}
